language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
env:
  - TORNADO_VERSION=1.2.1
  - TORNADO_VERSION=2.4.1
  - TORNADO_VERSION=3.0.2
matrix:
  exclude:
    - python: "2.5"
      env: TORNADO_VERSION=3.0.2
install:
  - "pip install simplejson --use-mirrors"
  - "pip install pycurl --use-mirrors"
  - "pip install tornado==$TORNADO_VERSION --use-mirrors"
script: py.test
notifications:
  email: false
